"""Inferential statistics for the CIFAR/DDPM run, for the paper.

The aggregate ratio tr Cov / tr Cov_h is a poor summary and the appendix says so:
at h=6 the kernel reference is nearly constant across conditions (its coefficient
of variation is small), so a ratio near 1 there certifies almost nothing. The
quantity with content is whether the model *tracks* the reference as the reference
moves, which is a slope across conditions, not a level.

This computes, per bandwidth:

    beta, R^2   OLS of log10(tr Cov measured) on log10(tr Cov_h) across the 48
                evaluation conditions, with the standard error of the slope and
                the number of decades the predictor spans. beta = 1 is the
                theory's prediction; beta = 0 would mean the model ignores the
                reference entirely.
    CV          coefficient of variation of the reference, which says how much
                range the regression actually had to work with.

and, pooled over the three h > 0 sweeps, the Spearman correlations of the ratio
against n_eff and against h -- the check that established n_eff, not h, is what
governs the discrepancy.

No scipy: the repo does not depend on it, and OLS with a slope standard error and
a tie-corrected Spearman are a dozen lines of numpy.

Reads:  results/exp3/_cifar_ddpm/reeval.json
Writes: results/exp3/_cifar_ddpm/stats.json, .../stats_table.tex,
        paper/figures/fig_cifar_ddpm_tracking.png

Usage:
    uv run python scripts/analyze_cifar_ddpm_stats.py
"""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

SRC = Path("results/exp3/_cifar_ddpm/reeval.json")
OUT = SRC.parent
FIG = Path("paper/figures/fig_cifar_ddpm_tracking.png")

# Okabe-Ito, matching scripts/make_paper_figures.py.
OI = {"black": "#000000", "orange": "#E69F00", "sky": "#56B4E9",
      "blue": "#0072B2", "vermillion": "#D55E00"}


def ols(x: np.ndarray, y: np.ndarray) -> dict[str, float]:
    """Slope, intercept, R^2 and the slope's standard error."""
    n = x.size
    xc, yc = x - x.mean(), y - y.mean()
    sxx = float((xc ** 2).sum())
    slope = float((xc * yc).sum() / sxx)
    intercept = float(y.mean() - slope * x.mean())
    resid = y - (intercept + slope * x)
    ss_res, ss_tot = float((resid ** 2).sum()), float((yc ** 2).sum())
    r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else float("nan")
    se = float(np.sqrt(ss_res / (n - 2) / sxx)) if n > 2 else float("nan")
    return {"slope": slope, "intercept": intercept, "r2": r2, "se": se, "n": int(n)}


def rankdata(a: np.ndarray) -> np.ndarray:
    """Ranks with ties averaged, as Spearman requires."""
    order = np.argsort(a, kind="mergesort")
    ranks = np.empty(a.size, float)
    ranks[order] = np.arange(1, a.size + 1, dtype=float)
    s = a[order]
    i = 0
    while i < s.size:
        j = i
        while j + 1 < s.size and s[j + 1] == s[i]:
            j += 1
        if j > i:
            ranks[order[i:j + 1]] = ranks[order[i:j + 1]].mean()
        i = j + 1
    return ranks


def spearman(a: np.ndarray, b: np.ndarray) -> float:
    ra, rb = rankdata(a), rankdata(b)
    ra, rb = ra - ra.mean(), rb - rb.mean()
    return float((ra * rb).sum() / np.sqrt((ra ** 2).sum() * (rb ** 2).sum()))


def main() -> None:
    rows = json.loads(SRC.read_text(encoding="utf-8"))
    per_h, pooled_ratio, pooled_neff, pooled_h = {}, [], [], []

    for r in rows:
        h = float(r["h"])
        if h == 0 or "ratio_per_condition" not in r:
            continue
        ref = np.asarray(r["trace_kernel_per_condition"], float)
        ratio = np.asarray(r["ratio_per_condition"], float)
        neff = np.asarray(r["n_eff_per_condition"], float)
        meas = ratio * ref

        ok = (ref > 0) & (meas > 0)
        fit = ols(np.log10(ref[ok]), np.log10(meas[ok]))
        fit["decades"] = float(np.ptp(np.log10(ref[ok])))
        fit["ref_cv"] = float(ref.std(ddof=1) / ref.mean())
        fit["ratio_median"] = float(r["ratio_median"])
        fit["ratio_ci"] = [float(r["ratio_ci_lo"]), float(r["ratio_ci_hi"])]
        fit["memorization_ratio"] = float(r["memorization_ratio"])
        fit["nn_correct_rate"] = float(r["nn_correct_rate"])
        fit["n_eff"] = float(r["n_eff"])
        per_h[f"{h:.0f}"] = fit

        pooled_ratio += list(ratio)
        pooled_neff += list(neff)
        pooled_h += [h] * ratio.size

    pooled = {
        "spearman_neff_ratio": spearman(np.array(pooled_neff), np.array(pooled_ratio)),
        "spearman_h_ratio": spearman(np.array(pooled_h), np.array(pooled_ratio)),
        "n": len(pooled_ratio),
    }

    out = {"per_h": per_h, "pooled": pooled}
    (OUT / "stats.json").write_text(json.dumps(out, indent=2), encoding="utf-8")

    lines = [r"% generated by scripts/analyze_cifar_ddpm_stats.py -- do not edit",
             r"\begin{tabular}{cccccc}", r"\toprule",
             r"$h$ & median ratio (95\% CI) & $\beta$ & $R^2$ & decades in "
             r"$\tr\Covh$ & CV of $\tr\Covh$\\", r"\midrule"]
    for h, f in sorted(per_h.items(), key=lambda kv: float(kv[0])):
        lines.append(
            f"{h} & {f['ratio_median']:.2f} "
            f"[{f['ratio_ci'][0]:.2f}, {f['ratio_ci'][1]:.2f}] & "
            f"{f['slope']:.3f} ({f['se']:.3f}) & {f['r2']:.3f} & "
            f"{f['decades']:.1f} & {f['ref_cv']:.3f}\\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    (OUT / "stats_table.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"{'h':>3} {'beta':>16} {'R2':>7} {'decades':>8} {'ref CV':>7} "
          f"{'median ratio':>22} {'memratio':>9}")
    for h, f in sorted(per_h.items(), key=lambda kv: float(kv[0])):
        print(f"{h:>3} {f['slope']:>9.3f} ({f['se']:.3f}) {f['r2']:>7.3f} "
              f"{f['decades']:>8.2f} {f['ref_cv']:>7.3f} "
              f"{f['ratio_median']:>8.2f} [{f['ratio_ci'][0]:.2f}, "
              f"{f['ratio_ci'][1]:.2f}] {f['memorization_ratio']:>9.3f}")
    print(f"\npooled over {pooled['n']} (condition, h) pairs with h > 0:")
    print(f"  Spearman(n_eff, ratio) = {pooled['spearman_neff_ratio']:+.3f}")
    print(f"  Spearman(h,     ratio) = {pooled['spearman_h_ratio']:+.3f}")
    make_figure(rows, per_h)
    print(f"\nSaved: {OUT}/stats.json, {OUT}/stats_table.tex, {FIG}")


def make_figure(rows, per_h) -> None:
    hs = sorted(per_h, key=float)
    by_h = {f"{float(r['h']):.0f}": r for r in rows if float(r["h"]) > 0}

    # One common range for every panel, so the panels are comparable and the
    # collapse of the h=6 cloud to a third of a decade is visible directly.
    pts = []
    for h in hs:
        r = by_h[h]
        ref = np.asarray(r["trace_kernel_per_condition"], float)
        meas = np.asarray(r["ratio_per_condition"], float) * ref
        ok = (ref > 0) & (meas > 0)
        pts += list(np.log10(ref[ok])) + list(np.log10(meas[ok]))
    lo, hi = min(pts) - 0.3, max(pts) + 0.3

    fig, axes = plt.subplots(1, len(hs), figsize=(3.3 * len(hs), 3.6), sharey=True)
    for ax, h in zip(np.atleast_1d(axes), hs):
        r, f = by_h[h], per_h[h]
        ref = np.asarray(r["trace_kernel_per_condition"], float)
        meas = np.asarray(r["ratio_per_condition"], float) * ref
        ok = (ref > 0) & (meas > 0)
        x, y = np.log10(ref[ok]), np.log10(meas[ok])
        ax.plot([lo, hi], [lo, hi], color=OI["black"], ls="--", lw=1.0,
                label=r"theory: $\beta=1$")
        xs = np.linspace(x.min(), x.max(), 2)
        ax.plot(xs, f["intercept"] + f["slope"] * xs, color=OI["vermillion"], lw=1.6,
                label=rf"fit: $\beta={f['slope']:.2f}$, $R^2={f['r2']:.2f}$")
        ax.scatter(x, y, s=20, color=OI["blue"], alpha=0.75, edgecolors="none",
                   zorder=3)
        ax.set_xlim(lo, hi); ax.set_ylim(lo, hi)
        ax.set_aspect("equal", adjustable="box")
        ax.set_title(rf"$h={h}$:  $\beta={f['slope']:.2f}$, "
                     rf"{f['decades']:.1f} decades", fontsize=10)
        ax.set_xlabel(r"$\log_{10}\,\mathrm{tr}\,\mathrm{Cov}_h$  (kernel theory)")
        ax.grid(alpha=0.3)
        ax.legend(fontsize=7, loc="upper left", framealpha=0.9)
    np.atleast_1d(axes)[0].set_ylabel(r"$\log_{10}\,\mathrm{tr}\,\mathrm{Cov}$  (measured)")
    fig.tight_layout()
    FIG.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(FIG, dpi=200)
    plt.close(fig)


if __name__ == "__main__":
    main()
